apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: app-b
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./app-b
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-apps
    namespace: flux-system
  targetNamespace: namespace-b
status: {}
