apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: app-a
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./app-a
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-apps
    namespace: flux-system
  targetNamespace: namespace-a
status: {}
