---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: enterprise
  namespace: flux-system
spec:
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./eksctl-clusters/apps/enterprise
  prune: true
  validation: client
  postBuild:
    substitute:
      CLUSTER_NAME: wge-2448
      BRANCH_NAME: cluster-wge-2448
      CHART_REPO: https://charts.dev.wkp.weave.works/dev/branches/scaling-integration
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: l7-ingress-visibility-wge
  namespace: flux-system
spec:
  description: L7 policy
  endpointSelector: { }
  ingress:
    - toPorts:
        - ports:
            - port: "8000"
              protocol: TCP
          rules:
            http:
              - method: POST
                path: "/v1/objects$"
              - method: POST
                path: "/v1/query$"

---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-all-within-namespace"
  namespace: flux-system
spec:
  description: "Allow all within namespace"
  endpointSelector: { }
  ingress:
    - fromEndpoints:
        - { }
  egress:
    - toEndpoints:
        - { }