---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: enterprise-scaling
  namespace: flux-system
spec:
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./eksctl-clusters/apps/enterprise
  prune: true
  validation: client
  postBuild:
    substitute:
      CLUSTER_NAME: wge-2448-scaling
      BRANCH_NAME: cluster-wge-2448
      CHART_REPO: https://charts.dev.wkp.weave.works/dev/branches/jp-oidc2