apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  creationTimestamp: null
  name: clusters-bases-kustomization
  namespace: flux-system
spec:
  interval: 10m0s
  path: eksctl-clusters/clusters/demo-01/bases
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
status: {}
