---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: enterprise
  namespace: flux-system
spec:
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./eksctl-clusters/apps/enterprise
  prune: true
  validation: client
  postBuild:
    substitute:
      CLUSTER_NAME: issue-wge-1713
      BRANCH_NAME: cluster-issue-wge-1713
      CHART_REPO: https://charts.dev.wkp.weave.works/dev/branches/1713-copy-clipboard-github-auth
