apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  creationTimestamp: null
  name: Hager
  namespace: flux-system
spec:
  dataFrom:
  - extract:
      key: /dev/waleed
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: SecretStore
    name: aws-secret-store
  target:
    creationPolicy: Owner
    name: new-external-secret
status:
  refreshTime: null
