apiVersion: v1
data:
    clientID: ENC[AES256_GCM,data:tUk64X+nUEPbHCWQ/D3vZ92FBO+WXfon,iv:S8O8G/WmGoVOGdRUOPZfcjsAqvsuSsGje7bx3YUnEaE=,tag:B59B7c6cq9r6kSgBahJuug==,type:str]
    clientSecret: ENC[AES256_GCM,data:goXlvdYRzc18rNHt5L+XVxmXiuAzJh1ob3oVrE+09PFv0MiAUzHRow7RgcG1G6Yi,iv:leNTxTBJiOF/C+2LjNC74CriR6mklhLYvBf54pJvgpc=,tag:3fbJsfHTOsBki/xdr07rRg==,type:str]
    issuerURL: ENC[AES256_GCM,data:lsbwWiY//obL6o1zhReBq4rPqR44sIWFqFUUXzja1b21kNglrvHT/hZW0jHNLTPe+RV2MUfj5ow=,iv:KuvRwVzW0x1fnGHlOUUUcMW+g4QmB2VsFBWTJ+4k8oQ=,tag:el+kZ0J2Ib++kaamA1gMbA==,type:str]
    redirectURL: ENC[AES256_GCM,data:fhw7QukNIjkJuz2rIQ1FXSNASwJD+D1k+vMRHWfeXSXz/9kQcfQetPnovDMDaFL5Thl8iQ==,iv:AgVBIdu0/tIIBYD2CPriepCVehbi8T4ywmPWAAE0fiA=,tag:Hs/mbEeA7hzooCV57S42Uw==,type:str]
kind: Secret
metadata:
    name: oidc-auth
    namespace: flux-system
sops:
    kms:
        - arn: arn:aws:kms:eu-north-1:894516026745:alias/sops-key
          created_at: "2022-09-20T13:54:57Z"
          enc: AQICAHiyI3Oxhzp88MEgh52h345Ka9LZpn4n9GqumbzeRmrAawGsNPk9FKyTYZXPRFsWJcLkAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMk4jnWxDDdtPKVlF4AgEQgDtCIyGH2Lax7MuQT7nOrzVs908I9DudYu0+N94f9REgWA+1UVJea65K7QGinVIXyeUKRDQ7HCwcDV5qhw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-09-20T13:55:01Z"
    mac: ENC[AES256_GCM,data:yGsgm7rHHQckAxtZv73o9Sah/8i2lEjzGNRoS58SnKwmkp1MZTkshHqKhxe7T/ujwVqAoPh1Wp6sJt+1+ocqpmvbHAAFjUlvnc4ygc9f5VpFJqWzizOaLG9UKUqaae9cO+1q3bHr2JTgJEY41hDR9eGqEoPNnCKztvh73PRCn38=,iv:n5+dVfoTlNZZwHsms1CpQcpniz6i+NkBp7hnix9Yqqo=,tag:u3ERYqz+bOG8TuLtSq3iAw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
