apiVersion: v1
data:
    clientID: ENC[AES256_GCM,data:1g7SpWVJjOaN9lwrs7bqmSaRL8z+TAY8,iv:ro0iLZ7FmuIrQCbRMF+yGbn6nAHXpy9kEep3iCWQiQU=,tag:M5g5zxUAITpa8busbhQI6A==,type:str]
    clientSecret: ENC[AES256_GCM,data:CH25G0D3DFU8Z8zIUvqNxLWMIGLq6kdbfRPgPpfbksHpDulHzsOAnuzNuQ9Btjzl,iv:1oYtTaH1g2lV8HwQKZWsz/xG6CP8OuAQXx+xE3pySUs=,tag:SOsI83d8QYP+rB+iCe/nbQ==,type:str]
    issuerURL: ${ISSUER_URL}
    redirectURL: ${REDIRECT_URL}
kind: Secret
metadata:
    name: oidc-auth
    namespace: flux-system
sops:
    kms:
        - arn: arn:aws:kms:eu-north-1:894516026745:alias/sops-key
          created_at: "2022-12-25T12:38:59Z"
          enc: AQICAHiyI3Oxhzp88MEgh52h345Ka9LZpn4n9GqumbzeRmrAawF8shAsQ4J86muDVYHKVcPMAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMMyj91zwN/+92AP+EAgEQgDsxwGgn57zxeMSugb6b54kO7omFfWq0y3T8G0eLwDRz+zUTclBN1UbikhPEYMWaRhg5v8NUWY6MIZnJMQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-25T12:39:00Z"
    mac: ENC[AES256_GCM,data:dnq9VT23QCQoay6vH9BX/OjHR4pCEn3rIApyQOoVAHnX82uXfH55xHPD/Skc4CjmmJJNSOaVZz6/++LbxNKFMs+7Jn9tH6XTqTI9rmCxIsD25gEFDjJLeIaXgJNX4/AtEtXJKdhZezub8WfH+KQGwVteMaeZd+zwosrpEMIsZc0=,iv:YmuPn+WgDCfX/Rwd3k41xjVyNzffwm+NvNp+Ot0F/p8=,tag:hKki9wV23r0pt7+M8kjH/A==,type:str]
    pgp: []
    encrypted_regex: ^(clientID|clientSecret)$
    version: 3.7.1
