apiVersion: v1
data:
    clientID: ENC[AES256_GCM,data:FoKSRL6+Eu6+UTf/dKmVP+lF3Gq8UXDx,iv:3uERpHR+ok0HLxEin0a6J+QnCjwSnV7ZGG5pbD2oRKg=,tag:W75EegSt2Fkz0NyueurVIQ==,type:str]
    clientSecret: ENC[AES256_GCM,data:XX6mTRfWrd/K1BBMFgI+5AR2+/3Gejsa5AMfHtpLxv1mssv4YUK6GwFBM9iMXrwn,iv:DP8H2JvZDjfNBzP93FFH+H2OMTag2MK+k4G4osZo7Ls=,tag:VaCWepcHrwyxyOpM/uXcdw==,type:str]
kind: Secret
metadata:
    name: oidc-auth
    namespace: flux-system
sops:
    kms:
        - arn: arn:aws:kms:eu-north-1:894516026745:alias/sops-key
          created_at: "2022-12-19T13:30:26Z"
          enc: AQICAHiyI3Oxhzp88MEgh52h345Ka9LZpn4n9GqumbzeRmrAawH6kuSkccElei5KPSoITbqQAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMePbGjYIKXoZkc+aQAgEQgDvXuZkDnA0VgzJSm48A9x0T8fcwWuvVNDOQig8DVl5Kf8TVJI/6aZSfmuTfBopYg3qZwsd5/aIwfWOhXw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-19T13:30:26Z"
    mac: ENC[AES256_GCM,data:UkHo8exNRlZ/zJ7h4OFOXmKU1wBrEsOK591vJOTbNUxfEGwa3VOdaVqNScWUAXfZM9i0GUqFjodrJ6QAU6RgVu5b3y9ux9S2f+hvGSFahFL46k9rpNLMg05ZSRLio/pF+zcSebGAtfwdwDz/1PoFWBGwyomkQE771rIkMQWULV8=,iv:QmGl+iiQLI8nlnrTkv8wqxfKhZ6OLMv4tKtruUo+B8Y=,tag:p77yNBWk00Jnayw4G4x9QQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
