apiVersion: v1
kind: Secret
metadata:
    name: mysecret
    namespace: flux-system
type: Opaque
data:
    user: ENC[AES256_GCM,data:cefYKcexxeo=,iv:1ZwQ4HaZ4n7LucFNPuRV3w+VsE62vgfBExCQFPH3CSc=,tag:KhGIw4bTvgewrxDX+h0aJA==,type:str]
    pass: ENC[AES256_GCM,data:iKGefcjU/JbaX5Q2EQH3HQ==,iv:QBcQgksOXcWuQRgm+s7OGu33I2MA3YXB1p6k0tsGDt0=,tag:38nqv1Uk85WwXBhvlAWZug==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-north-1:894516026745:alias/sops-key
          created_at: "2022-09-20T09:30:36Z"
          enc: AQICAHiyI3Oxhzp88MEgh52h345Ka9LZpn4n9GqumbzeRmrAawHJRtDxdC/wYba9y0XPugdFAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMcVKVfL+k9bZLEJunAgEQgDvxB1ri6a4M4ahgtcBGxR/UhzbA7P/KK7UiaSzpJLliWhVv6s4ze4wU+KGwLW5wiKXqrJodeUUfifNCkQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-09-20T09:30:37Z"
    mac: ENC[AES256_GCM,data:34Jxg1DkNEViTPvhCyuM0rW4cgcmkwRkm88e9ZT7aAck9JCG+WjUt7Z8jfgekm8SbGekKVgX1YtxM3nG0BYJOYm0gUJNJicTPAqI4jFriYHw+bPbWlU8hpi5Atz8b/zcCQdzfo1ou1bl5aq9py5+vs97+t8FB08+vGpyZf957GY=,iv:/r9tzeuxYniIG+ZsWYakXmA9ekVNc/6rZ/wl5uPs1XM=,tag:fnUIC2CBYCxbJHTS/frp9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
