apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: shared-secrets
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./eksctl-clusters/shared-secrets
  prune: true
  decryption:
    provider: sops
  postBuild:
    substitute:
      ISSUER_URL: aHR0cHM6Ly9oZy1leHRlcm5hbC1zZWNyZXQtZGV4LmVuZy1zYW5kYm94LndlYXZlLndvcmtz
      REDIRECT_URL: aHR0cHM6Ly9oZy1leHRlcm5hbC1zZWNyZXQuZW5nLXNhbmRib3gud2VhdmUud29ya3Mvb2F1dGgyL2NhbGxiYWNr
