---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: tempaltes
  namespace: flux-system
spec:
  interval: 30s
  dependsOn:
    - name: enterprise
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./eksctl-clusters/clusters/saeed-test-02/capi-templates
  prune: true
  validation: client
