---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: templates
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: enterprise
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./eksctl-clusters/clusters/saeed-test-02/templates
  prune: true
  validation: client
