apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: multi-container
  namespace: default
spec:
  interval: 10m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./eksctl-clusters/clusters/test-add-violated-app/multi-container-app
  prune: true
  timeout: 1m