apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: weave-gitops-enterprise-charts-scaling
  namespace: flux-system
spec:
  interval: 10m
  secretRef:
    name: weave-gitops-enterprise-credentials
  url: https://charts.dev.wkp.weave.works/dev/branches/jp-oidc2
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops-enterprise-scaling
  namespace: flux-system
spec:
  chart:
    spec:
      chart: mccp
      version: ">= 0.0.0-0"
      sourceRef:
        kind: HelmRepository
        name: weave-gitops-enterprise-charts-scaling
        namespace: flux-system
  dependsOn:
    - name: cert-manager
  interval: 10m0s
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    crds: Skip
  values:
    config:
      capi:
        templates:
          namespace: default
        clusters:
          namespace: ""
        repositoryURL: "https://github.com/weaveworks/clusters-config"
        repositoryPath: "./eksctl-clusters/clusters/${CLUSTER_NAME}/clusters"
        repositoryClustersPath: "./eksctl-clusters/clusters/${CLUSTER_NAME}"
        baseBranch: "${BRANCH_NAME}"
      oidc:
        enabled: false
        issuerURL: https://${CLUSTER_NAME}-dex.eng-sandbox.weave.works
        redirectURL: https://${CLUSTER_NAME}.eng-sandbox.weave.works/oauth2/callback
        clientCredentialsSecret: oidc-auth
    tls:
      enabled: false
    enablePipelines: false
    enableTerraformUI: false
    enableExplorer: false
    policy-agent:
      enabled: false
      config:
        accountId: "${CLUSTER_NAME}-user"
        clusterId: "${CLUSTER_NAME}"
    pipeline-controller:
      promotion:
        service:
          enabled: false
        ingress:
          enabled: false
          className: "public-nginx"
          annotations:
            external-dns.alpha.kubernetes.io/hostname: promotions-${CLUSTER_NAME}.eng-sandbox.weave.works
          hosts:
            - host: promotions-${CLUSTER_NAME}.eng-sandbox.weave.works
              paths:
                - path: /
                  pathType: ImplementationSpecific
    ingress:
      enabled: true
      className: "public-nginx"
      annotations:
        # kubernetes.io/tls-acme: "true"
        external-dns.alpha.kubernetes.io/hostname: wge-scaling.eng-sandbox.weave.works
        # service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
      hosts:
        - host: wge-scaling.eng-sandbox.weave.works
          paths:
            - path: /
              pathType: ImplementationSpecific
