apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: dex
  namespace: flux-system
spec:
  interval: 30m
  url: https://charts.dexidp.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex
  namespace: dex
spec:
  chart:
    spec:
      chart: dex
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: dex
        namespace: flux-system
      version: 0.6.5
  interval: 5m
  targetNamespace: dex
  values:
    config:
      enablePasswordDB: true
      issuer: https://${CLUSTER_NAME}-dex.eng-sandbox.weave.works
      staticClients:
      - id: weave-gitops-app
        name: Weave Gitops
        redirectURIs:
        - https://${CLUSTER_NAME}.eng-sandbox.weave.works/oauth2/callback
        secret: B7Skl2cfSoOQgOhIkeqxx1uJjWxjCFoEEymk
      staticPasswords:
      - email: admin@test.invalid
        hash: $2y$10$5b/iK/HHCyYRk7S0iNaqn.mb36QbC0sSNKR5Rnhh/cITPgdviwfcu
        userID: 1111240c-6f22-4da7-94e1-8d52d260f0bd
        username: admin
      - email: admin-apps@test.invalid
        hash: $2y$10$5b/iK/HHCyYRk7S0iNaqn.mb36QbC0sSNKR5Rnhh/cITPgdviwfcu
        userID: 1111240c-6f22-4da7-94e1-8d52d260f0bd
        username: admin-apps
      - email: ro@test.invalid
        hash: $2y$10$5b/iK/HHCyYRk7S0iNaqn.mb36QbC0sSNKR5Rnhh/cITPgdviwfcu
        userID: 1111240c-6f22-4da7-94e1-8d52d260f0bd
        username: ro
      - email: ro-apps@test.invalid
        hash: $2y$10$5b/iK/HHCyYRk7S0iNaqn.mb36QbC0sSNKR5Rnhh/cITPgdviwfcu
        userID: fceaf51f-f8a7-4aff-809e-1b1568e96528
        username: ro-apps
      storage:
        type: memory
      web:
        http: 0.0.0.0:5556
    image:
      tag: v2.31.0
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"
        external-dns.alpha.kubernetes.io/hostname: ${CLUSTER_NAME}-dex.eng-sandbox.weave.works
        # service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
      hosts:
        - host: ${CLUSTER_NAME}-dex.eng-sandbox.weave.works
          paths:
            - path: /
              pathType: ImplementationSpecific
