---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nginx-84
  namespace: flux-stress
spec:
  interval: 1h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-84
  namespace: flux-stress
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: nginx-84
        namespace: flux-stress
      interval: 1m