apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ahsayde-cluster
  region: eu-north-1
  version: "1.23"
  tags:
    environment: "ahsayde-cluster"
    delete-after: "2"
    team: "timberworlf"

iam:
  withOIDC: true
  serviceRoleARN: "arn:aws:iam::894516026745:role/WeaveEksClusterRole"
  serviceAccounts:
  - metadata:
      name: kustomize-controller
      namespace: flux-system
    attachPolicyARNs:
    - "arn:aws:iam::894516026745:policy/WeaveSopsKmsDecrypt"
    roleName: eksctl-ahsayde-cluster-sops-decrypt-role
    roleOnly: true

# Enable private access to the API server.
vpc:
  clusterEndpoints:
    privateAccess: true
    publicAccess: true

nodeGroups:
  - name: ahsayde-cluster-ng-1
    instanceType: t3.medium
    minSize: 3
    maxSize: 3
    desiredCapacity: 3
    volumeSize: 10
    privateNetworking: true
    tags:
      environment: "ahsayde-cluster"
      delete-after: "2"
      team: "timberworlf"
    propagateASGTags: true
    iam:
      instanceProfileARN: "arn:aws:iam::894516026745:instance-profile/WeaveEksWorkerNodeRole"

gitops:
  flux:
    gitProvider: github
    flags:
      owner: "weaveworks"
      repository: "clusters-config"
      private: "true"
      branch: "cluster-ahsayde-cluster"
      namespace: "flux-system"
      path: "eksctl-clusters/clusters/ahsayde-cluster"
