apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: create-secret-api
  region: eu-north-1
  version: "1.24"
  tags:
    environment: "create-secret-api"
    delete-after: "7"
    team: "TimberWolf"

iam:
  withOIDC: true
  serviceRoleARN: "arn:aws:iam::894516026745:role/WeaveEksClusterRole"
  serviceAccounts:
  - metadata:
      name: kustomize-controller
      namespace: flux-system
    attachPolicyARNs:
    - "arn:aws:iam::894516026745:policy/WeaveSopsKmsDecrypt"
    roleName: eksctl-create-secret-api-sops-decrypt-role
    roleOnly: true

# Enable private access to the API server.
vpc:
  clusterEndpoints:
    privateAccess: true
    publicAccess: true

nodeGroups:
  - name: create-secret-api-ng-1
    instanceType: t3.medium
    minSize: 3
    maxSize: 3
    desiredCapacity: 3
    volumeSize: 10
    privateNetworking: true
    tags:
      environment: "create-secret-api"
      delete-after: "7"
      team: "TimberWolf"
    propagateASGTags: true
    iam:
      instanceProfileARN: "arn:aws:iam::894516026745:instance-profile/WeaveEksWorkerNodeRole"

gitops:
  flux:
    gitProvider: github
    flags:
      owner: "weaveworks"
      repository: "clusters-config"
      private: "true"
      branch: "cluster-create-secret-api"
      namespace: "flux-system"
      path: "eksctl-clusters/clusters/create-secret-api"
