---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: l7-ingress-visibility-wge
  namespace: flux-system
spec:
  description: L7 policy
  endpointSelector: { }
  ingress:
    - toPorts:
        - ports:
            - port: "8000"
              protocol: TCP
          rules:
            http:
              - method: POST
                path: "/v1/objects$"
