apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: policy-config
  region: eu-north-1
  version: "1.24"
  tags:
    environment: "policy-config"
    delete-after: "7"
    team: "timber-wolf"

iam:
  withOIDC: true
  serviceRoleARN: "arn:aws:iam::894516026745:role/WeaveEksClusterRole"
  serviceAccounts:
  - metadata:
      name: kustomize-controller
      namespace: flux-system
    attachPolicyARNs:
    - "arn:aws:iam::894516026745:policy/WeaveSopsKmsDecrypt"
    roleName: eksctl-policy-config-sops-decrypt-role
    roleOnly: true
  - metadata:
      name: external-dns
      namespace: external-dns
    attachPolicyARNs:
    - "arn:aws:iam::894516026745:policy/AllowExternalDNSUpdates"
    roleName: eksctl-policy-config-route53-external-dns-role
    roleOnly: false # create role and annotated service account

# Enable private access to the API server.
vpc:
  clusterEndpoints:
    privateAccess: true
    publicAccess: true

nodeGroups:
  - name: policy-config-ng-1
    instanceType: t3.medium
    minSize: 3
    maxSize: 3
    desiredCapacity: 3
    volumeSize: 10
    privateNetworking: true
    tags:
      environment: "policy-config"
      delete-after: "7"
      team: "timber-wolf"
    propagateASGTags: true
    iam:
      instanceProfileARN: "arn:aws:iam::894516026745:instance-profile/WeaveEksWorkerNodeRole"

gitops:
  flux:
    gitProvider: github
    flags:
      owner: "weaveworks"
      repository: "clusters-config"
      private: "true"
      branch: "cluster-policy-config"
      namespace: "flux-system"
      path: "eksctl-clusters/clusters/policy-config"
