apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: wge-2448
  region: eu-north-1
  version: "1.24"
  tags:
    environment: "wge-2448"
    delete-after: "20"
    team: "platform"

iam:
  withOIDC: true
  serviceRoleARN: "arn:aws:iam::894516026745:role/WeaveEksClusterRole"
  serviceAccounts:
    - metadata:
        name: kustomize-controller
        namespace: flux-system
      attachPolicyARNs:
        - "arn:aws:iam::894516026745:policy/WeaveSopsKmsDecrypt"
      roleName: eksctl-wge-2448-sops-decrypt-role
      roleOnly: true
    - metadata:
        name: external-dns
        namespace: external-dns
      attachPolicyARNs:
        - "arn:aws:iam::894516026745:policy/AllowExternalDNSUpdates"
      roleName: eksctl-wge-2448-route53-external-dns-role
      roleOnly: false # create role and annotated service account

# Enable private access to the API server.
vpc:
  clusterEndpoints:
    privateAccess: true
    publicAccess: true

nodeGroups:
  - name: wge-2448-ng-1
    instanceType: t3.medium
    minSize: 3
    maxSize: 4
    desiredCapacity: 4
    volumeSize: 10
    privateNetworking: true
    tags:
      environment: "wge-2448"
      delete-after: "10"
      team: "platform"
    propagateASGTags: true
    iam:
      instanceProfileARN: "arn:aws:iam::894516026745:instance-profile/WeaveEksWorkerNodeRole"

gitops:
  flux:
    gitProvider: github
    flags:
      owner: "weaveworks"
      repository: "clusters-config"
      private: "true"
      branch: "cluster-wge-2448"
      namespace: "flux-system"
      path: "eksctl-clusters/clusters/wge-2448"
