apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: workspaces-list-test
  region: eu-north-1
  version: "1.23"
  tags:
    environment: "workspaces-list-test"
    delete-after: "7"
    team: "Timberwolf"

iam:
  withOIDC: true
  serviceRoleARN: "arn:aws:iam::894516026745:role/WeaveEksClusterRole"
  serviceAccounts:
  - metadata:
      name: kustomize-controller
      namespace: flux-system
    attachPolicyARNs:
    - "arn:aws:iam::894516026745:policy/WeaveSopsKmsDecrypt"
    roleName: eksctl-workspaces-list-test-sops-decrypt-role
    roleOnly: true

# Enable private access to the API server.
vpc:
  clusterEndpoints:
    privateAccess: true
    publicAccess: true

nodeGroups:
  - name: workspaces-list-test-ng-1
    instanceType: t3.medium
    minSize: 3
    maxSize: 3
    desiredCapacity: 3
    volumeSize: 10
    privateNetworking: true
    tags:
      environment: "workspaces-list-test"
      delete-after: "7"
      team: "Timberwolf"
    propagateASGTags: true
    iam:
      instanceProfileARN: "arn:aws:iam::894516026745:instance-profile/WeaveEksWorkerNodeRole"

gitops:
  flux:
    gitProvider: github
    flags:
      owner: "weaveworks"
      repository: "clusters-config"
      private: "true"
      branch: "cluster-workspaces-list-test"
      namespace: "flux-system"
      path: "eksctl-clusters/clusters/workspaces-list-test"
