apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  creationTimestamp: null
  name: test
  namespace: flux-system
spec:
  data:
  - remoteRef:
      key: /dev/secretsdemo
      property: testkey
    secretKey: testkey
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: SecretStore
    name: aws-secret-store
  target:
    creationPolicy: Owner
    name: test
status:
  refreshTime: null
