apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  creationTimestamp: null
  name: test2
  namespace: flux-system
spec:
  data:
  - remoteRef:
      key: /dev/secretsdemo
      property: testkey
    secretKey: sdsd
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: SecretStore
    name: aws-secret-store
  target:
    creationPolicy: Owner
    name: ss
status:
  refreshTime: null
