# Note: In Flux, we can't have dependencies between Flux Kustomization and HelmRelease,
# so we install external-secrets-operator through a HelmRelease
# and the Secrets CRs (SecretStore, ExternalSecret) through a Flux Kustomization:
# 1- Deploy CRDs through Flux Kustomization
# 2- Deploy the operator HelmRelease with installCRDs=false.
# 3- Deploy CRs (SecretStore, ExternalSecret) through another Flux Kustomization
# See: https://external-secrets.io/v0.4.3/examples-gitops-using-fluxcd/#the-problem

# GitRepository
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 10m
  ref:
    branch: main
  url: http://github.com/external-secrets/external-secrets
---
# HelmRepository
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 10m
  url: https://charts.external-secrets.io
---
# external secrets crds
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-secrets-crds
  namespace: flux-system
spec:
  interval: 10m
  path: ./deploy/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: external-secrets
---
# external secrets helm release
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  # Override Release name to avoid the pattern Namespace-Release
  # Ref: https://fluxcd.io/docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.HelmRelease
  releaseName: external-secrets
  targetNamespace: external-secrets
  interval: 10m
  chart:
    spec:
      chart: external-secrets
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  values:
    installCRDs: false

  # Ref: https://fluxcd.io/docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.Install
  install:
    createNamespace: true
---
# external secrets secrets
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-secrets-secrets
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-crds
  interval: 10m
  # This is where the custom resources live (SecretStore, ExternalSecret)
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./secrets
  prune: true
  validation: client