apiVersion: v2
name: secrets-store-config
icon: https://raw.githubusercontent.com/external-secrets/external-secrets/main/assets/round_eso_logo.png
description: A Weaveworks Helm chart to configure secret stores and secrets using External Secrets Operator
type: application
version: 0.0.1-0
kubeVersion: ">=1.16.0-0"
home: https://github.com/weaveworks/profiles-catalog

keywords:
- external-secrets
- secrets-manager
- parameter-store
- azure-key-vault
- vault

maintainers:
- name: Weaveworks
  email: support@weave.works

annotations:
  "weave.works/profile": external-secrets-store-config
  "weave.works/category": Secrets Management
  "weave.works/layer": layer-4
  "weave.works/links": |
    - name: Upstream Project
      url: https://github.com/external-secrets/external-secrets
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
