apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  creationTimestamp: null
  name: multi-container
  namespace: default
spec:
  interval: 10m0s
  path: ./eksctl-clusters/clusters/test-add-violated-app/multi-container-app/multi-container-manifest.yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
status: {}
