apiVersion: gitops.weave.works/v1alpha1
kind: GitopsCluster
metadata:
  annotations:
    templates.weave.works/create-request: '{"head_branch":"create-clusters-branch-u956b3","title":"Creates
      cluster test-leaf","description":"This PR creates a new cluster","template_name":"aws-eks","parameter_values":{"AWS_REGION":"eu-north-1","CLUSTER_NAME":"test-leaf","INSTANCE_TYPE":"t3.medium","KUBERNETES_VERSION":"v1.23.7","OWNER_EMAIL":"waleed.hamam@weave.works","SSH_KEY_NAME":"test","WORKER_MACHINE_COUNT":"1"},"commit_message":"Creates
      capi cluster","credentials":{},"values":[{"name":"cert-manager","version":"0.0.8","layer":"layer-0"},{"name":"weave-policy-agent","version":"0.5.3","layer":"layer-1"}]}'
  labels:
    templates.weave.works/template-name: aws-eks
    templates.weave.works/template-namespace: default
    weave.works/apps: capd
    weave.works/capi: bootstrap
    weave.works/flux: bootstrap
  name: test-leaf
  namespace: default
spec:
  capiClusterRef:
    name: test-leaf

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    templates.weave.works/template-name: aws-eks
    templates.weave.works/template-namespace: default
  name: test-leaf
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.120.0.0/20
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: test-leaf-control-plane
  infrastructureRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: test-leaf-control-plane

---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: AWSManagedControlPlane
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: aws-eks
    templates.weave.works/template-namespace: default
  name: test-leaf-control-plane
  namespace: default
spec:
  additionalTags:
    creator: waleed.hamam@weave.works
  iamAuthenticatorConfig:
    mapRoles:
    - groups:
      - system:masters
      rolearn: arn:aws:iam::894516026745:role/AdministratorAccess
      username: admin
    - groups:
      - system:masters
      rolearn: arn:aws:iam::894516026745:role/WeaveEksEditor
      username: admin
  region: eu-north-1
  sshKeyName: test
  version: v1.23.7

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: aws-eks
    templates.weave.works/template-namespace: default
  name: test-leaf-pool-0
  namespace: default
spec:
  clusterName: test-leaf
  replicas: 1
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: test-leaf
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSManagedMachinePool
        name: test-leaf-pool-0

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSManagedMachinePool
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: aws-eks
    templates.weave.works/template-namespace: default
  name: test-leaf-pool-0
  namespace: default
spec:
  additionalTags:
    creator: waleed.hamam@weave.works
  instanceType: t3.medium
