apiVersion: gitops.weave.works/v1alpha1
kind: GitopsCluster
metadata:
  annotations:
    templates.weave.works/create-request: '{"repository_url":"https://github.com/weaveworks/clusters-config","head_branch":"wge-create-branch-gznau","title":"Creates
      resource saeed-test-eks","description":"This PR creates a leaf-eks-2 instance","template_name":"leaf-eks-2","parameter_values":{"AMI_TYPE":"ami-03f710e174aa82316","AWS_REGION":"eu-north-1","CLUSTER_NAME":"saeed-test-eks","CLUSTER_VERSION":"1.24"},"commit_message":"Creates
      leaf-eks-2 instance","credentials":{},"template_namespace":"default","template_kind":"GitOpsTemplate"}'
  labels:
    templates.weave.works/template-name: leaf-eks-2
    templates.weave.works/template-namespace: default
  name: saeed-test-eks
  namespace: flux-system
spec:
  secretRef:
    name: saeed-test-eks-kubeconfig

---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  labels:
    templates.weave.works/template-name: leaf-eks-2
    templates.weave.works/template-namespace: default
  name: saeed-test-eks-core
  namespace: flux-system
spec:
  approvePlan: auto
  destroyResourcesOnDeletion: true
  interval: 1h
  path: ./eksctl-clusters/tf
  retryInterval: 20s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  vars:
  - name: cluster_name
    value: saeed-test-eks
  - name: cluster_version
    value: "1.24"
  - name: region
    value: eu-north-1
  - name: ami_type
    value: ami-03f710e174aa82316
  writeOutputsToSecret:
    name: saeed-test-eks-core-outputs
  runnerPodTemplate:
    spec:
      envFrom:
      - secretRef:
          name: aws-credentials
