---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: templates
  namespace: flux-system
spec:
  interval: 30s
  dependsOn:
    - name: enterprise
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./eksctl-clusters/clusters/${CLUSTER_NAME}/capi-templates
  prune: true
