---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: enterprise
  namespace: flux-system
spec:
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./eksctl-clusters/apps/enterprise
  prune: true
  postBuild:
    substitute:
      CLUSTER_NAME: policy-config-cards
      BRANCH_NAME: cluster-policy-config-cards
      CHART_REPO: https://charts.dev.wkp.weave.works/dev/branches/format-policy-params-cards
