apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: saeed-test-01
  region: eu-north-1
  version: "1.23"
  tags:
    environment: "saeed-test-01"

managedNodeGroups:
  - name: saeed-test-01-ng-1
    instanceType: t3.medium
    minSize: 2
    maxSize: 2
    desiredCapacity: 2
    volumeSize: 10
    tags:
      environment: "saeed-test-01"
    propagateASGTags: true
    iam:
      withAddonPolicies:
        certManager: true

gitops:
  flux:
    gitProvider: github
    flags:
      owner: "weaveworks"
      repository: "clusters-config"
      private: "true"
      branch: "main"
      namespace: "flux-system"
      path: "eksctl-clusters/clusters/saeed-test-01/management"
