apiVersion: pac.weave.works/v2beta2
kind: PolicyConfig
metadata:
  creationTimestamp: null
  name: New PolicyConfig
spec:
  config:
    weave.policies.tenancy.bar-tenant-allowed-application-deploy:
      parameters:
        namespaces:
        - bar-ns
        - ' foobar-ns '
  match:
    apps:
    - kind: HelmRelease
      name: dex
      namespace: dex
    - kind: HelmRelease
      name: ingress-nginx
      namespace: flux-system
    - kind: Kustomization
      name: podinfo
      namespace: apps
    - kind: Kustomization
      name: enterprise
      namespace: flux-system
    - kind: Kustomization
      name: flux-system
      namespace: flux-system
    - kind: Kustomization
      name: common
      namespace: flux-system
    - kind: HelmRelease
      name: weave-gitops-enterprise
      namespace: flux-system
status: {}
