apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  labels:
    weave.works/applied-layer: layer-1
  name: ingress-nginx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        apiVersion: source.toolkit.fluxcd.io/v1beta2
        kind: HelmRepository
        name: weaveworks-charts
        namespace: flux-system
      version: 0.0.11
  dependsOn:
  - name: cert-manager
  install:
    crds: CreateReplace
    createNamespace: true
  interval: 1m0s
  targetNamespace: ingress-nginx
  upgrade:
    crds: CreateReplace
  values:
    ingress-nginx:
      controller:
        metrics:
          enabled: true
        podAnnotations:
          "prometheus.io/scrape": true
          "prometheus.io/port": 10254
        service:
          annotations:
            networking.gke.io/load-balancer-type: Internal
            service.beta.kubernetes.io/aws-load-balancer-internal: "true"
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
            service.beta.kubernetes.io/oci-load-balancer-internal: "true"
