apiVersion: capi.weave.works/v1alpha1
kind: CAPITemplate
metadata:
  name: capa-template-development
  namespace: default
spec:
  description: This is the std. CAPA template
  params:
    - name: CLUSTER_NAME
      description: This is used for the cluster naming.
    - name: NAMESPACE
      description: Namespace to create the cluster in.
    - name: AWS_REGION
      description: AWS Region to create cluster
      options: ["eu-north-1"]
    - name: AWS_SSH_KEY_NAME
      description: AWS ssh key name
      options: ["weave-gitops-pesto"]
    - name: KUBERNETES_VERSION
      description: The version of Kubernetes to use.
      options: ["v1.22.9", "v1.23.3"]
    - name: AWS_CONTROL_PLANE_MACHINE_TYPE
      description: Control plane machine instane type.
      options: ["t3.nano", "t3.micro", "t3.small", "t3.medium", "t3.large", "t3.xlarge", "t3.2xlarge"]
    - name: CONTROL_PLANE_MACHINE_COUNT
      description: Number of control planes
      options: ["1", "2", "3", "4", "5"]
    - name: AWS_NODE_MACHINE_TYPE
      description: Node machine instane type.
      options: ["t3.nano", "t3.micro", "t3.small", "t3.medium", "t3.large", "t3.xlarge", "t3.2xlarge"]
    - name: WORKER_MACHINE_COUNT
      description: Number of control planes
      options: ["1", "2", "3", "4", "5", "6", "7"]
  resourcetemplates:
    - apiVersion: gitops.weave.works/v1alpha1
      kind: GitopsCluster
      metadata:
        name: "${CLUSTER_NAME}"
        namespace: "${NAMESPACE}"
        labels:
          weave.works/capi: bootstrap
      spec:
        capiClusterRef:
          name: "${CLUSTER_NAME}"
    - apiVersion: cluster.x-k8s.io/v1beta1
      kind: Cluster
      metadata:
        name: "${CLUSTER_NAME}"
        namespace: "${NAMESPACE}"
        labels:
          cni: calico
      spec:
        clusterNetwork:
          pods:
            cidrBlocks:
            - 192.168.0.0/16
        controlPlaneRef:
          apiVersion: controlplane.cluster.x-k8s.io/v1beta1
          kind: AWSManagedControlPlane
          name: "${CLUSTER_NAME}-control-plane"
        infrastructureRef:
          apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
          kind: AWSManagedControlPlane
          name: "${CLUSTER_NAME}"
          version: "${KUBERNETES_VERSION}"
    - apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: AWSManagedControlPlane
      metadata:
        name: "${CLUSTER_NAME}"
        namespace: "${NAMESPACE}"
      spec:
        region: "${AWS_REGION}"
    - apiVersion: cluster.x-k8s.io/v1beta1
      kind: MachineDeployment
      metadata:
        name: "${CLUSTER_NAME}-md-0"
        namespace: "${NAMESPACE}"
      spec:
        clusterName: "${CLUSTER_NAME}"
        replicas: ${WORKER_MACHINE_COUNT}
        selector:
          matchLabels: null
        template:
          spec:
            bootstrap:
              configRef:
                apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
                kind: EKSConfigTemplate
                name: "${CLUSTER_NAME}-md-0"
            clusterName: "${CLUSTER_NAME}"
            infrastructureRef:
              apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
              kind: AWSMachineTemplate
              name: "${CLUSTER_NAME}-md-0"
            version: "${KUBERNETES_VERSION}"
    - apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: AWSMachineTemplate
      metadata:
        name: "${CLUSTER_NAME}-md-0"
        namespace: "${NAMESPACE}"
      spec:
        template:
          spec:
            iamInstanceProfile: nodes.cluster-api-provider-aws.sigs.k8s.io
            instanceType: "${AWS_NODE_MACHINE_TYPE}"
            sshKeyName: "${AWS_SSH_KEY_NAME}"
