apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app-templates
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./eksctl-clusters/weave-gitops-platform/templates/application
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
