---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clusters-default-tenants-kustomization
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./eksctl-clusters/clusters/default/tenants
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
