apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: create-sops-secrets-validation
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: secrets
  path: ./eksctl-clusters/apps/validation/secrets/sops
