apiVersion: templates.weave.works/v1alpha2
kind: GitOpsTemplate
metadata:
  name: leaf
  namespace: default
  labels:
    weave.works/template-type: terraform
  annotations:
    templates.weave.works/profiles-enabled: "true"
    # templates.weave.works/kustomizations-enabled: "false"
    # templates.weave.works/credentials-enabled: "false"
spec:
  description: This is a sample WGE template that will be translated into a tf-controller specific template.
  renderType: templating
  params:
    - name: CLUSTER_NAME
      description: Name of the cluster.
    - name: CLUSTER_VERSION
      description: Version of the cluster.
      options: ['1.23', '1.24']
      default: "1.24"
    - name: AWS_REGION
      description: AWS region to deploy cluster.
      default: eu-north-1
    - name: INSTANCE_TYPE
      description: Instance type of nodes in cluster.
      options: ['t3.medium']
    - name: AMI_TYPE
      description: AMI.
      options: ['ami-03f710e174aa82316']
  resourcetemplates:
    - path: clusters/management/clusters/{{ .params.CLUSTER_NAME }}.yaml
      content:
        - apiVersion: gitops.weave.works/v1alpha1
          kind: GitopsCluster
          metadata:
            name: '{{ .params.CLUSTER_NAME }}'
            namespace: flux-system
          spec:
            secretRef:
              name: '{{ .params.CLUSTER_NAME }}-kubeconfig'
        - apiVersion: infra.contrib.fluxcd.io/v1alpha1
          kind: Terraform
          metadata:
            name: '{{ .params.CLUSTER_NAME }}-core'
            namespace: flux-system
          spec:
            interval: 1h
            retryInterval: 20s
            path: ./cluster-templates/leaf-cluster-core
            approvePlan: auto
            destroyResourcesOnDeletion: true
            writeOutputsToSecret:
              name: '{{ .params.CLUSTER_NAME }}-core-outputs'
            backendConfig:
              customConfiguration: |
                backend "s3" {
                  bucket         = "dish-20276-terraform-state"
                  key            = "leaf-clusters/{{ .params.CLUSTER_NAME }}/leaf-cluster-core/terraform.tfstate"
                  region         = "{{ .params.AWS_REGION }}"
                  encrypt        = true
                  dynamodb_table = "dish-20276-terraform-state"
                }
            vars:
              - name: cluster_name
                value: '{{ .params.CLUSTER_NAME }}'
              - name: cluster_version
                value: '{{ .params.CLUSTER_VERSION }}'
              - name: region
                value: '{{ .params.AWS_REGION }}'
              - name: vpc_cidr
                value: '{{ .params.VPC_CIDR }}'
              - name: public_subnet_count
                value: '{{ .params.PUBLIC_SUBNET_COUNT }}'
              - name: private_subnet_count
                value: '{{ .params.PRIVATE_SUBNET_COUNT }}'
            sourceRef:
              kind: GitRepository
              name: terraform
              namespace: flux-system
        - apiVersion: infra.contrib.fluxcd.io/v1alpha1
          kind: Terraform
          metadata:
            name: '{{ .params.CLUSTER_NAME }}-config'
            namespace: flux-system
          spec:
            dependsOn:
              - name: '{{ .params.CLUSTER_NAME }}-core'
            interval: 1h
            retryInterval: 20s
            path: ./cluster-templates/leaf-cluster-config
            approvePlan: auto
            destroyResourcesOnDeletion: true
            backendConfig:
              customConfiguration: |
                backend "s3" {
                  bucket         = "dish-20276-terraform-state"
                  key            = "leaf-clusters/{{ .params.CLUSTER_NAME }}/leaf-cluster-config/terraform.tfstate"
                  region         = "{{ .params.AWS_REGION }}"
                  encrypt        = true
                  dynamodb_table = "dish-20276-terraform-state"
                }
            vars:
              - name: cluster_name
                value: '{{ .params.CLUSTER_NAME }}'
              - name: region
                value: '{{ .params.AWS_REGION }}'
              - name: target_path
                value: 'clusters/default/{{ .params.CLUSTER_NAME }}'
              - name: desired_size
                value: '{{ .params.DESIRED_SIZE }}'
              - name: min_size
                value: '{{ .params.MIN_SIZE }}'
              - name: max_size
                value: '{{ .params.MAX_SIZE }}'
              - name: capacity_type
                value: '{{ .params.CAPACITY_TYPE }}'
              - name: instance_type
                value: '{{ .params.INSTANCE_TYPE }}'
              - name: shrink
                value: '{{ .params.SHRINK }}'
            varsFrom:
              - kind: ConfigMap
                name: leaf-cluster-config
              - kind: Secret
                name: leaf-cluster-auth
            sourceRef:
              kind: GitRepository
              name: terraform
              namespace: flux-system
