---
apiVersion: templates.weave.works/v1alpha2
kind: GitOpsTemplate
metadata:
  name: eks-leaf-cluster
  namespace: default
  labels:
    weave.works/template-type: terraform
  # annotations:
  #   templates.weave.works/profiles-enabled: "true"
spec:
  description: This is a sample WGE template that will be translated into a tf-controller specific template.
  renderType: templating
  params:
    - name: CLUSTER_VERSION
      description: Version of the cluster.
      options: ['1.23', '1.24']
    - name: CLUSTER_NAME
      description: Name of the cluster.
    - name: AWS_REGION
      description: AWS region to deploy cluster.
      options: ['eu-north-1']
    - name: INSTANCE_TYPE
      description: Instance type of nodes in cluster.
      options: ['t3.medium']
    - name: AMI_TYPE
      description: AMI.
      options: ['ami-03f710e174aa82316']

  resourcetemplates:
    - content:
      - apiVersion: gitops.weave.works/v1alpha1
        kind: GitopsCluster
        metadata:
          name: "hh"
          namespace: flux-system
        # spec:
        #   secretRef:
        #     name: "${CLUSTER_NAME}-kubeconfig"
      # - apiVersion: infra.contrib.fluxcd.io/v1alpha1
      #   kind: Terraform
      #   metadata:
      #     name: "${CLUSTER_NAME}"
      #     namespace: flux-system
      #   spec:
      #     interval: 1h
      #     path: ./eksctl-clusters/tf
      #     approvePlan: auto
      #     destroyResourcesOnDeletion: true
      #     alwaysCleanupRunnerPod: true
      #     writeOutputsToSecret:
      #         name: "${CLUSTER_NAME}-core-outputs"
      #     vars:
      #       - name: cluster_name
      #         value: '{{ .params.CLUSTER_NAME }}'
      #       - name: cluster_version
      #         value: '{{ .params.CLUSTER_VERSION }}'
      #       - name: region
      #         value: '{{ .params.AWS_REGION }}'
      #       - name: ami_type
      #         value: '{{ .params.AMI_TYPE }}'
      #     sourceRef:
      #       kind: GitRepository
      #       name: flux-system
      #       namespace: flux-system
      # path: "eksctl-clusters/clusters/saeed-terraform/clusters/${CLUSTER_VERSION}.yaml"
      
