apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: secrets
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: fluxga-validate-secrets
  secretRef:
    name: flux-system
  url: ssh://git@github.com/weaveworks/clusters-config
