apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  labels:
    weave.works/applied-layer: layer-2
  name: prometheus
  namespace: flux-system
spec:
  chart:
    spec:
      chart: prometheus
      sourceRef:
        apiVersion: source.toolkit.fluxcd.io/v1beta2
        kind: HelmRepository
        name: weaveworks-charts
        namespace: flux-system
      version: 0.0.9
  dependsOn:
  - name: ingress-nginx
  install:
    crds: CreateReplace
    createNamespace: true
  interval: 1m0s
  targetNamespace: prometheus
  upgrade:
    crds: CreateReplace
  values:
    kube-prometheus-stack:
      alertmanager:
        ingress:
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/rewrite-target: /$1
            nginx.ingress.kubernetes.io/use-regex: "true"
          enabled: true
          paths:
          - /alertmanager/?(.*)
      enabled: true
      grafana:
        grafana.ini:
          server:
            root_url: https://localhost:3000/grafana/
            serve_from_sub_path: true
        ingress:
          annotations:
            kubernetes.io/ingress.class: nginx
          enabled: true
          path: /grafana/?(.*)
