apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  labels:
    weave.works/applied-layer: layer-2
  name: flagger
  namespace: flux-system
spec:
  chart:
    spec:
      chart: flagger
      sourceRef:
        apiVersion: source.toolkit.fluxcd.io/v1beta2
        kind: HelmRepository
        name: weaveworks-charts
        namespace: flux-system
      version: 0.0.4
  dependsOn:
    - name: ingress-nginx
  install:
    crds: CreateReplace
    createNamespace: true
  interval: 1m0s
  targetNamespace: flagger
  upgrade:
    crds: CreateReplace
  values:
    flagger:
      meshProvider: nginx
      prometheus:
        install: true
    loadtester:
      logLevel: debug
