apiVersion: gitops.weave.works/v1alpha1
kind: GitopsCluster
metadata:
  annotations:
    templates.weave.works/create-request: '{"repository_url":"https://github.com/weaveworks/clusters-config","head_branch":"wge-create-branch-woodfq","title":"Creates
      resource test","description":"This PR creates a aws-eks instance","template_name":"aws-eks","parameter_values":{"AWS_REGION":"eu-north-1","CLUSTER_NAME":"test","INSTANCE_TYPE":"t3.medium","KUBERNETES_VERSION":"v1.24.1","OWNER_EMAIL":"waleed.hamam@weave.works","SSH_KEY_NAME":"waleed","WORKER_MACHINE_COUNT":"1"},"commit_message":"Creates
      aws-eks instance","credentials":{},"template_namespace":"default","template_kind":"CAPITemplate"}'
  labels:
    templates.weave.works/template-name: aws-eks
    templates.weave.works/template-namespace: default
    weave.works/capi: bootstrap
  name: test
  namespace: default
spec:
  capiClusterRef:
    name: test

---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: aws-eks
    templates.weave.works/template-namespace: default
  name: test-core
  namespace: flux-system
spec:
  approvePlan: auto
  destroyResourcesOnDeletion: true
  interval: 1h
  path: ./eksctl-clusters/leaf-terraform
  retryInterval: 20s
  sourceRef:
    kind: GitRepository
    name: terraform
    namespace: flux-system
  vars:
  - name: CLUSTER_NAME
    value: test
  - name: AWS_REGION
    value: eu-north-1
  - name: target_path
    value: clusters/default/test
  - name: INSTANCE_TYPE
    value: t3.medium
  varsFrom:
  - kind: ConfigMap
    name: leaf-cluster-config
  - kind: Secret
    name: leaf-cluster-auth
  writeOutputsToSecret:
    name: test-core-outputs

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    templates.weave.works/template-name: aws-eks
    templates.weave.works/template-namespace: default
  name: test
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.120.0.0/20
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: test-control-plane
  infrastructureRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: test-control-plane

---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: AWSManagedControlPlane
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: aws-eks
    templates.weave.works/template-namespace: default
  name: test-control-plane
  namespace: default
spec:
  additionalTags:
    creator: waleed.hamam@weave.works
  iamAuthenticatorConfig:
    mapRoles:
    - groups:
      - system:masters
      rolearn: arn:aws:iam::894516026745:role/AdministratorAccess
      username: admin
    - groups:
      - system:masters
      rolearn: arn:aws:iam::894516026745:role/WeaveEksEditor
      username: admin
  region: eu-north-1
  sshKeyName: waleed
  version: v1.24.1

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: aws-eks
    templates.weave.works/template-namespace: default
  name: test-pool-0
  namespace: default
spec:
  clusterName: test
  replicas: 1
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: test
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSManagedMachinePool
        name: test-pool-0

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSManagedMachinePool
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: aws-eks
    templates.weave.works/template-namespace: default
  name: test-pool-0
  namespace: default
spec:
  additionalTags:
    creator: waleed.hamam@weave.works
  instanceType: t3.medium
