apiVersion: gitops.weave.works/v1alpha1
kind: GitopsCluster
metadata:
  labels:
    templates.weave.works/template-name: aws-eks
    templates.weave.works/template-namespace: default
    weave.works/capi: bootstrap
  name: dev
  namespace: test-namespace
  annotations:
    templates.weave.works/create-request: "{\"repository_url\":\"https://github.com/weaveworks/clusters-config\",\"head_branch\":\"wge-create-branch-ozm5u\",\"base_branch\":\"cluster-test-page-refreshing\",\"title\":\"Create resource dev\",\"description\":\"This PR creates a aws-eks instance\",\"template_name\":\"aws-eks\",\"parameter_values\":{\"AWS_REGION\":\"eu-north-1\",\"CLUSTER_NAME\":\"dev\",\"CLUSTER_NAMESPACE\":\"test-namespace\",\"INSTANCE_TYPE\":\"t3.medium\",\"KUBERNETES_VERSION\":\"v1.24.1\",\"OWNER_EMAIL\":\"tagreed.anany@weave.works\",\"SSH_KEY_NAME\":\"weave-gitops-pesto\",\"WORKER_MACHINE_COUNT\":\"1\"},\"commit_message\":\"Create aws-eks instance\",\"credentials\":{},\"template_namespace\":\"temp-namespace\",\"template_kind\":\"CAPITemplate\"}"
    templates.weave.works/created-files: "{\"files\":[\"eksctl-clusters/clusters/test-page-refreshing/clusters/default/dev.yaml\"]}"
spec:
  capiClusterRef:
    name: dev

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    templates.weave.works/template-name: aws-eks
    templates.weave.works/template-namespace: default
  name: dev
  namespace: test-namespace
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.120.0.0/20
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: dev-control-plane
  infrastructureRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: dev-control-plane

---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: AWSManagedControlPlane
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    templates.weave.works/create-request: "{\"repository_url\":\"https://github.com/weaveworks/clusters-config\",\"head_branch\":\"wge-create-branch-ozm5u\",\"base_branch\":\"cluster-test-page-refreshing\",\"title\":\"Create resource dev\",\"description\":\"This PR creates a aws-eks instance\",\"template_name\":\"aws-eks\",\"parameter_values\":{\"AWS_REGION\":\"eu-north-1\",\"CLUSTER_NAME\":\"dev\",\"CLUSTER_NAMESPACE\":\"test-namespace\",\"INSTANCE_TYPE\":\"t3.medium\",\"KUBERNETES_VERSION\":\"v1.24.1\",\"OWNER_EMAIL\":\"tagreed.anany@weave.works\",\"SSH_KEY_NAME\":\"weave-gitops-pesto\",\"WORKER_MACHINE_COUNT\":\"1\"},\"commit_message\":\"Create aws-eks instance\",\"credentials\":{},\"template_namespace\":\"temp-namespace\",\"template_kind\":\"CAPITemplate\"}"
    templates.weave.works/created-files: "{\"files\":[\"eksctl-clusters/clusters/test-page-refreshing/clusters/default/dev.yaml\"]}"
  labels:
    templates.weave.works/template-name: aws-eks
    templates.weave.works/template-namespace: default
  name: dev-control-plane
  namespace: test-namespace
spec:
  additionalTags:
    creator: tagreed.anany@weave.works
  iamAuthenticatorConfig:
    mapRoles:
    - groups:
      - system:masters
      rolearn: arn:aws:iam::894516026745:role/AdministratorAccess
      username: admin
    - groups:
      - system:masters
      rolearn: arn:aws:iam::894516026745:role/WeaveEksEditor
      username: admin
  region: eu-north-1
  sshKeyName: weave-gitops-pesto
  version: v1.24.1

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    templates.weave.works/create-request: "{\"repository_url\":\"https://github.com/weaveworks/clusters-config\",\"head_branch\":\"wge-create-branch-ozm5u\",\"base_branch\":\"cluster-test-page-refreshing\",\"title\":\"Create resource dev\",\"description\":\"This PR creates a aws-eks instance\",\"template_name\":\"aws-eks\",\"parameter_values\":{\"AWS_REGION\":\"eu-north-1\",\"CLUSTER_NAME\":\"dev\",\"CLUSTER_NAMESPACE\":\"test-namespace\",\"INSTANCE_TYPE\":\"t3.medium\",\"KUBERNETES_VERSION\":\"v1.24.1\",\"OWNER_EMAIL\":\"tagreed.anany@weave.works\",\"SSH_KEY_NAME\":\"weave-gitops-pesto\",\"WORKER_MACHINE_COUNT\":\"1\"},\"commit_message\":\"Create aws-eks instance\",\"credentials\":{},\"template_namespace\":\"temp-namespace\",\"template_kind\":\"CAPITemplate\"}"
    templates.weave.works/created-files: "{\"files\":[\"eksctl-clusters/clusters/test-page-refreshing/clusters/default/dev.yaml\"]}"
  labels:
    templates.weave.works/template-name: aws-eks
    templates.weave.works/template-namespace: default
  name: dev-pool-0
  namespace: test-namespace
spec:
  clusterName: dev
  replicas: 1
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: dev
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSManagedMachinePool
        name: dev-pool-0

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSManagedMachinePool
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    templates.weave.works/create-request: "{\"repository_url\":\"https://github.com/weaveworks/clusters-config\",\"head_branch\":\"wge-create-branch-ozm5u\",\"base_branch\":\"cluster-test-page-refreshing\",\"title\":\"Create resource dev\",\"description\":\"This PR creates a aws-eks instance\",\"template_name\":\"aws-eks\",\"parameter_values\":{\"AWS_REGION\":\"eu-north-1\",\"CLUSTER_NAME\":\"dev\",\"CLUSTER_NAMESPACE\":\"test-namespace\",\"INSTANCE_TYPE\":\"t3.medium\",\"KUBERNETES_VERSION\":\"v1.24.1\",\"OWNER_EMAIL\":\"tagreed.anany@weave.works\",\"SSH_KEY_NAME\":\"weave-gitops-pesto\",\"WORKER_MACHINE_COUNT\":\"1\"},\"commit_message\":\"Create aws-eks instance\",\"credentials\":{},\"template_namespace\":\"temp-namespace\",\"template_kind\":\"CAPITemplate\"}"
    templates.weave.works/created-files: "{\"files\":[\"eksctl-clusters/clusters/test-page-refreshing/clusters/default/dev.yaml\"]}"
  labels:
    templates.weave.works/template-name: aws-eks
    templates.weave.works/template-namespace: default
  name: dev-pool-0
  namespace: test-namespace
spec:
  additionalTags:
    creator: tagreed.anany@weave.works
  instanceType: t3.medium
