apiVersion: gitops.weave.works/v1alpha1
kind: GitopsCluster
metadata:
  labels:
    templates.weave.works/template-name: vcluster-template-development
    templates.weave.works/template-namespace: default
    weave.works/capi: bootstrap
  name: dev
  namespace: test-namespace
  annotations:
    templates.weave.works/create-request: "{\"repository_url\":\"https://github.com/weaveworks/clusters-config\",\"head_branch\":\"wge-create-branch-uil20l\",\"base_branch\":\"cluster-test-cluster-details-issue\",\"title\":\"Create resource dev\",\"description\":\"This PR creates a vcluster-template-development instance\",\"template_name\":\"vcluster-template-development\",\"parameter_values\":{\"CLUSTER_NAME\":\"dev\",\"KUBERNETES_VERSION\":\"1.22.0\",\"NAMESPACE\":\"test-namespace\"},\"commit_message\":\"Create vcluster-template-development instance\",\"credentials\":{},\"values\":[{\"name\":\"ingress-nginx\",\"version\":\"0.0.18\",\"layer\":\"layer-1\"}],\"template_namespace\":\"default\",\"template_kind\":\"GitOpsTemplate\"}"
    templates.weave.works/created-files: "{\"files\":[\"eksctl-clusters/clusters/test-cluster-details-issue/clusters/test-namespace/dev.yaml\"]}"
spec:
  capiClusterRef:
    name: dev

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    templates.weave.works/template-name: vcluster-template-development
    templates.weave.works/template-namespace: default
  name: dev
  namespace: test-namespace
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: dev
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: dev

---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  labels:
    templates.weave.works/template-name: vcluster-template-development
    templates.weave.works/template-namespace: default
  name: dev
  namespace: test-namespace
spec:
  helmRelease:
    values: |
      syncer:
        extraArgs:
          - "--tls-san=dev.test-namespace.svc"
  kubernetesVersion: 1.22.0
