apiVersion: v1
data:
  test: ENC[AES256_GCM,data:T+BX2e8edmA=,iv:8IBm6IHUUhaEUJiY4xXdR+BIWvH4jL8zjzIf2p4zTrY=,tag:MSKTJa+SpiRsmVNDJoUg8w==,type:str]
kind: Secret
metadata:
  name: test
  namespace: test
sops:
  age: null
  azure_kv: null
  encrypted_regex: ^(data|stringData)$
  gcp_kms: null
  hc_vault: null
  kms: null
  lastmodified: "2023-08-02T07:05:23Z"
  mac: ENC[AES256_GCM,data:fnkJYwk3c5jdGXgjwXoYh1M9wPluZgET2EmRsxNACFbuS2zfmXLV//7pcTjhMlx96fEUyz7Is1MJHfCt8S/CHVkojDCFrjLMgljEkZ4CROXx1qevMZ5wbuj6lRjRupqYJclLTujhwImW0gTYwLXF3BYUwUVwlhIknsSsC/8tEKg=,iv:d5lF7cLoxrttlbOPkirnzd4ohordu8KuVWCiYwoXbP0=,tag:UvhFa5yJ2O4CJMbYgIYCiQ==,type:str]
  pgp:
  - created_at: "2023-08-02T07:05:23Z"
    enc: |
      -----BEGIN PGP MESSAGE-----

      hQIMA34OXF3lS6nZAQ//edX8KV4aaK18e5CWaU5ijhAm02wQgpGPyOb3XkXLm0+8
      mKLKGiiJpfAKfyf2EiFYq3Gn0dlEMTxhPBBgyozTRb2idcsA5o2dx3JECeZp7FHk
      J9r0s6IqHNlQctB+APAaAy7WLZ3dZxjNVubuXOh8vlEa8LwsCCho0BB3HTJFBpXW
      H3BGKYa9663ut5PZtmNkoLoXh34sDUeGRzJxRc/oOevurTRWWBnLM5sH/TDJ2WTF
      Xy+0IM25De8CoGdUwIroLgtRED32/C+W8MFZPxkpRHWJ9xhghYJloOCsKp0HV8m/
      0/KjHm2JqBc9H+fnaVOdPXGX+3LTug8dB86LqEcnSdghSl//1t9OSkbGq4Nrcg87
      gnFHhtRUX/kfFUAwFrdzYRUXqzJKBWhcsFkT4myXS0BwHTH+iCRUHOgjIU76jRBn
      AW6y7vsppttukVEPhHMtocIKbWTEpmy3+ZRy2dPOOLJ4RP4c1nQatWUpQ2s/YxSf
      tEatl3FNjiaU9SS3QCTiLuKOyK7ho1bv22HxrAFY7ihhHngHf+n1IE49gcDF9tsj
      GILsu174QRXNetqeRLmNteCb5X8Qg8GJ+yf+MO3KNRUjGAJEwoLX2jGdT+GymEdz
      nE2kt4F1EKSfVqeKJ6UwiDlCoAdxMOvDIzmXnhu9WF0xE3PZLMV6cFSPBiKWYOXU
      aAEJAhCIWRPwjpiSWteJp/eaKA7+VPSsEBqv5lE2rrN6xyyBysB940TEdtuMv7pK
      t5Ke2x23bdwEEGjwwzAyYf1madOC2EhAuNT6o1CIjuXuLb8PyC6pHhxfz9omJCyl
      0XyVSPIGr6S9
      =aIXW
      -----END PGP MESSAGE-----
    fp: 0e97c0f5df2997c667ddffec03ea65b409f41c3b
  version: ""
