apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 20s
  timeout: 1m0s
  url: https://waleedhammam.github.io/external-secrets-helm/
