apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  creationTimestamp: null
  name: tes
  namespace: flux-system
spec:
  dataFrom:
  - extract:
      key: test
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: SecretStore
    name: aws-secrets-manager
  target:
    creationPolicy: Owner
    name: test
status:
  refreshTime: null
