apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: new-secret
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: secret-to-be-created
    creationPolicy: Owner
  data:
  - secretKey: new-secret
    remoteRef:
      key: "test_external_secrets"
      property: "testwaleed_secretmanagment"