apiVersion: v1
kind: Secret
metadata:
  name: promotion-credentials
  namespace: flux-system
type: Opaque
data:
  password: Z2hwX2dac3FxWnFCMjlkTmcwRXlFZnVhRmtad3VteDJyOTRScmFORg==
  token: Z2hwX2dac3FxWnFCMjlkTmcwRXlFZnVhRmtad3VteDJyOTRScmFORg==
  username: d2VhdmUtZ2l0b3BzLWJvdA==