apiVersion: v1
data:
  username: YWRtaW4= #admin
  password: JDJhJDEwJHVuWDZ0c2RQNTFWNEl2aldqazhSMnVoOC9aMmR3ck5QUHdoZjNzU2Fkbkw5bTNTbFp1SzdX  #adminpass
kind: Secret
metadata:
  name: cluster-user-auth
  namespace: flux-system
