

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: weave-gitops-enterprise-charts
  namespace: flux-system
spec:
  interval: 60m
  secretRef:
    name: weave-gitops-enterprise-credentials
  url: https://charts.dev.wkp.weave.works/releases/charts-v3
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops-enterprise
  namespace: flux-system
spec:
  chart:
    spec:
      chart: mccp
      version: "0.9.5"
      sourceRef:
        kind: HelmRepository
        name: weave-gitops-enterprise-charts
        namespace: flux-system
  interval: 10m0s
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  values:
    ingress:
      enabled: false
    config:
      capi:
        templates:
          namespace: default
        clusters:
          namespace: ""
        repositoryURL: "https://github.com/weaveworks/clusters-config"
        repositoryPath: "./eksctl-clusters/clusters/${CLUSTER_NAME}/clusters"
        repositoryClustersPath: "./eksctl-clusters/clusters/${CLUSTER_NAME}"
        baseBranch: "${BRANCH_NAME}"
      oidc:
        enabled: true
        issuerURL: http://dex-dex.dex.svc.cluster.local:5556
        redirectURL: http://localhost:9001/oauth2/callback
        clientCredentialsSecret: oidc-auth
    tls:
      enabled: false
    # enablePipelines: true
    # enableTerraformUI: true
