
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: weave-gitops-enterprise-charts
  namespace: flux-system
spec:
  interval: 10m
  secretRef:
    name: weave-gitops-enterprise-credentials
  url: ${CHART_REPO}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops-enterprise
  namespace: flux-system
spec:
  chart:
    spec:
      chart: mccp
      version: ">= 0.0.0-0"
      sourceRef:
        kind: HelmRepository
        name: weave-gitops-enterprise-charts
        namespace: flux-system
  dependsOn:
  - name: cert-manager
  interval: 10m0s
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  values:
    config:
      capi:
        templates:
          namespace: default
        clusters:
          namespace: ""
        repositoryURL: "https://github.com/weaveworks/clusters-config"
        repositoryPath: "./eksctl-clusters/clusters/${CLUSTER_NAME}/clusters"
        repositoryClustersPath: "./eksctl-clusters/clusters/${CLUSTER_NAME}"
        baseBranch: "${BRANCH_NAME}"
      oidc:
        enabled: true
        clientCredentialsSecret: oidc-auth
    tls:
      enabled: false
    enablePipelines: true
    enableTerraformUI: true
    policy-agent:
      enabled: true
      config:
        accountId: "${CLUSTER_NAME}-user"
        clusterId: "${CLUSTER_NAME}"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"
        external-dns.alpha.kubernetes.io/hostname: ${CLUSTER_NAME}.eng-sandbox.weave.works
        # service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
      hosts:
        - host: ${CLUSTER_NAME}.eng-sandbox.weave.works
          paths:
            - path: /
              pathType: ImplementationSpecific
