apiVersion: v1
kind: Namespace
metadata:
  name: postgres
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: postgres
  namespace: postgres
spec:
  interval: 10m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: postgres
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: '12.1.9'
      sourceRef:
        kind: HelmRepository
        name: postgres
        namespace: postgres
      interval: 1m
