apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-system-dev
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: secrets-runtime
  secretRef:
    name: flux-system
  url: ssh://git@github.com/weaveworks/clusters-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system-dev
  path: ./eksctl-clusters/apps/external-secrets
  prune: true
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system-dev
  path: ./eksctl-clusters/apps/external-secrets
  prune: true
  validation: client