---
apiVersion: v1
kind: Secret
metadata:
  name: promotion-credentials
  namespace: flux-system
type: Opaque
data:
  username: d2VhdmUtZ2l0b3BzLWJvdA==
  password: Z2hwX2dac3FxWnFCMjlkTmcwRXlFZnVhRmtad3VteDJyOTRScmFORg==
  token: Z2hwX2dac3FxWnFCMjlkTmcwRXlFZnVhRmtad3VteDJyOTRScmFORg==
---
apiVersion: pipelines.weave.works/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-01
  namespace: flux-system
spec:
  appRef:
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: podinfo
  environments:
    - name: dev
      targets:
        - namespace: podinfo-01-dev
    - name: prod
      targets:
        - namespace: podinfo-01-prod
  promotion:
    manual: true
    strategy:
      pull-request:
        type: github
        url: https://github.com/weaveworks/clusters-config
        branch: cluster-waiting-approval
        secretRef:
          name: promotion-credentials
