apiVersion: v1
kind: Namespace
metadata:
  name: podinfo-01-prod
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: podinfo
  namespace: podinfo-01-prod
spec:
  interval: 1h
  url: https://stefanprodan.github.io/podinfo
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo-01-prod
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: "6.0.3" # {"$promotion": "flux-system:pipeline-01:prod"}
      sourceRef:
        kind: HelmRepository
        name: podinfo
      interval: 1m
