apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  creationTimestamp: null
  name: elnew-secret
  namespace: flux-system
spec:
  dataFrom:
  - extract:
      key: /dev/waleed
  refreshInterval: 10s
  secretStoreRef:
    kind: SecretStore
    name: aws-secret-store
  target:
    creationPolicy: Owner
    name: brand-new-secret
status:
  refreshTime: null
