apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1m0s
  timeout: 1m0s
  url: "https://kubernetes.github.io/ingress-nginx"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  labels:
    weave.works/applied-layer: layer-1
  name: ingress-nginx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        apiVersion: source.toolkit.fluxcd.io/v1beta2
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: 4.2.5
  install:
    crds: CreateReplace
    createNamespace: true
  interval: 1m0s
  targetNamespace: flux-system
  upgrade:
    crds: CreateReplace
  values:
    controller:
      ingressClassResource:
        enabled: true
        name: public-nginx
        default: false
        controllerValue: "k8s.io/public-ingress-nginx"
      ingressClass: public-nginx
      service:
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ${SSL_CERTIFICATE_ARN}
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
          service.beta.kubernetes.io/aws-load-balancer-internal: "false"
        targetPorts:
          http: http
          https: http
