apiVersion: v1
kind: Secret
metadata:
  name: test
  namespace: default
sops:
  age:
  - enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMEFPaWovdjRvelVKTVhS
      bnJJYm1kbDRxVHlDeTZMVkphb2RBYW12NUcwCnFrY05YRUk5RU5tOUVxZmZVbWZq
      ZktJY2w2VGgvWCtXenVmanhYQXpkRmsKLS0tIDJRQTBHdFJKS2ppdUNCcVBmanFU
      RnNuQlZpRHNWZTRoWERnTzRKUS9CRFUKioTskMe0mcr2TJsCw/n7g/weX2YmMfkA
      B7zoXYkNNhJP5bUtY89ZLnIjp+p5N9oHrnRO2M+j9693yjqV9u/E6A==
      -----END AGE ENCRYPTED FILE-----
    recipient: age1t5fg4mxjyupt25d8szjrltcylsjv3ctqfw3panpavew40s29x3nqt9nsr3
  azure_kv: null
  encrypted_regex: ^(data|stringData)$
  gcp_kms: null
  hc_vault: null
  kms: null
  lastmodified: "2023-03-23T01:26:50Z"
  mac: ENC[AES256_GCM,data:gesnIgt4Tlj7rHSmHz/QYIzSfCGhftO2TwmryX1e0PEeEDBn7jbyBmaqp+9m5R2YozhQcqSctmTsfelRZz5rQeCg1/zYuVRhztVpdTRjPD4yjDxylSxtwEiRGchjOm9RocrPI0QUqjN8LARhqUcCpBV8xRlWcaF+I/k9NpeuuDQ=,iv:28JOnhnB+TxHbkui+g9wd8Kc31FDYzoW7OrEyrrJh9Y=,tag:GafVC8l0DK5/LCMJrj7J2g==,type:str]
  pgp: null
  version: ""
stringData:
  string: ENC[AES256_GCM,data:MtYvX9v1mEfqSBo=,iv:1a1f1gt5Ja2yZUDcHin9+fIkdEhpFRFug+BtOvj28N4=,tag:P0WarTAixFMivUBWjPSo2g==,type:str]
