apiVersion: v1
kind: Secret
metadata:
  name: test
  namespace: default
sops:
  age:
  - enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldEQzblBidU44M09QZXdI
      bzlnVEJMVWwvM1FwcENva245dDVsWGdQNFhrCjRERG45cGJRUktmOHZTU3lDL1F4
      NGM2cTROYnBaZnFSYXRsZ0NTRXlDdk0KLS0tIG9qbjJhbWR1MTZkdkx3SzJ3OHd0
      MHpyQ3dTSkxIbG1EUEJid0xLNUt0d1UKo398wT0+NE+b1KLvhIeIHJQnvtRLBFPp
      esGBp/OG2c5yZC9PrMa7vmCS8opaVU82Pc3Dyc51bL+lZGyLv/XwXA==
      -----END AGE ENCRYPTED FILE-----
    recipient: age1t5fg4mxjyupt25d8szjrltcylsjv3ctqfw3panpavew40s29x3nqt9nsr3
  azure_kv: null
  encrypted_regex: ^(data|stringData)$
  gcp_kms: null
  hc_vault: null
  kms: null
  lastmodified: "2023-03-22T16:48:24Z"
  mac: ENC[AES256_GCM,data:p03bRtFyyWbw+Y8nD2XZgFG+L+llt1Su9poyVT3VQg0o0Hc5XPT9DaRAMPqxON54EAHnS6zZ/MRup6z9k2Mh0xp8OGooy1FkqnQGEH24quMn6OO9RuO9IAnps4l7iY52fP3RvLXuTXluMMtqFlkGvWgtCkFzU3TOuvxevk8fyg4=,iv:L0V8O0yaBmWhw99/Z3o7r5itERAmKR3FO34k56tKf0E=,tag:5rljwyRgWPZ2SHkonXWDEA==,type:str]
  pgp: null
  version: ""
stringData:
  string: ENC[AES256_GCM,data:e5eZIE330Haq6Ic=,iv:EdOZcB1MwrLcRKhHuUJ+FcXiu07ZHiSt9CKuGyAcXV0=,tag:zpiWwRipbMdsAQCuGYS6hA==,type:str]
