---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: enterprise
  namespace: flux-system
spec:
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./eksctl-clusters/apps/enterprise
  prune: true
  validation: client
  postBuild:
    substitute:
      CLUSTER_NAME: workspaces-apis
      BRANCH_NAME: cluster-workspaces-apis
      CHART_REPO: https://charts.dev.wkp.weave.works/dev/branches/2807-replace-placeholder-text-with-command-on-workspace-details-yaml-tabs
