---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: enterprise
  namespace: flux-system
spec:
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./eksctl-clusters/apps/enterprise
  prune: true
  validation: client
  postBuild:
    substitute:
      CLUSTER_NAME: test-cluster-details-issue
      BRANCH_NAME: cluster-test-cluster-details-issue
      CHART_REPO: https://charts.dev.wkp.weave.works/releases/charts-v3
