apiVersion: templates.weave.works/v1alpha2
kind: GitOpsTemplate
metadata:
  name: deploy-podinfo-helmchart-with-container
  namespace: devteam1
  annotations:
    templates.weave.works/profiles-enabled: "false"
    templates.weave.works/kustomizations-enabled: "false"
    templates.weave.works/credentials-enabled: "false"
  labels:
    weave.works/template-type: application
spec:
  description: Add a helm chart with this template
  params:
    - name: CLUSTER_NAME
      description: Target Cluster Name
      default: devteam1-host25-cluster30
    - name: CLUSTER_NAMESPACE
      description: The cluster namespace for the target cluster
      default: devteam1
    - name: TARGET_NAMESPACE
      description: Target Namespace
      default: devteam1
    - name: CREATE_NAMESPACE
      description: Create or not Create Namespace
      options: ['true', 'false']
      default: "false"
    - name: HELM_RESOURCE_NAME
      description: Helm Resource Name
      default: devteam1-helm-podinfo
    - name: HELM_RELEASE_NAMESPACE
      description: Helm Release Namespace
      default: flux-system
    - name: CHART_NAME
      description: Name of the Chart to install
      default: podinfo
    - name: CHART_VERSION
      description: Version of the helm chart to usp
      default: 0.0.15
    - name: CONTAINER_IMAGE
      description: The container image to use with the Helm chart
      default: ghcr.io/stefanprodan/podinfo:6.0.0
    - name: FQDN
      description: FQDN to reach the app
      default: podinfo.devteam1.weavegitops.com

  resourcetemplates:
    - path: clusters/${CLUSTER_NAMESPACE}/${CLUSTER_NAME}/${HELM_RESOURCE_NAME}.yaml
      content:
      - apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: ${HELM_RESOURCE_NAME}
          namespace: ${HELM_RELEASE_NAMESPACE}
          annotations:
            metadata.weave.works/dashboard.ApplicationURL: http://${FQDN}
            metadata.weave.works/target.cluster: ${CLUSTER_NAME}
        spec:
          chart:
            spec:
              chart: ${CHART_NAME}
              sourceRef:
                apiVersion: source.toolkit.fluxcd.io/v1beta2
                kind: HelmRepository
                name: app-charts
                namespace: flux-system
              version: ${CHART_VERSION}
          interval: 10m0s
          install: 
            createNamespace: ${CREATE_NAMESPACE}
          targetNamespace: ${TARGET_NAMESPACE}
          values:
            deployment:
              image: ${CONTAINER_IMAGE}
            ingress:
              host: ${FQDN}
