apiVersion: gitops.weave.works/v1alpha1
kind: GitopsCluster
metadata:
  annotations:
    templates.weave.works/create-request:
      '{"repository_url":"https://github.com/weaveworks/clusters-config","head_branch":"wge-create-branch-xmfsek","title":"Creates
      resource ","description":"This PR creates a aks-template instance","template_name":"aks-template","parameter_values":{"AZURE_CLIENT_ID":"626d016a-9788-442c-b062-3ed7e64340db","AZURE_CLUSTER_IDENTITY_SECRET_NAME":"cluster-identity-secret","AZURE_CLUSTER_IDENTITY_SECRET_NAMESPACE":"default","AZURE_LOCATION":"eastus","AZURE_NODE_MACHINE_TYPE":"Standard_D2s_v3","AZURE_RESOURCE_GROUP":"team-pesto-use1","AZURE_SUBSCRIPTION_ID":"ace37984-3d07-4051-9002-d5a52c0ae14b","AZURE_TENANT_ID":"3747a928-2079-440f-8f0f-ab1be2a7c058","CLUSTER_IDENTITY_NAME":"cluster-identity","CLUSTER_NAME":"pesto-conformance2023","KUBERNETES_VERSION":"1.25.5","NAMESPACE":"default","WORKER_MACHINE_COUNT":"3"},"commit_message":"Creates
      aks-template instance","credentials":{},"template_namespace":"default","template_kind":"GitOpsTemplate"}'
  labels:
    templates.weave.works/template-name: aks-template
    templates.weave.works/template-namespace: default
  name: pesto-conformance2023
  namespace: default
spec:
  capiClusterRef:
    name: pesto-conformance2023

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    templates.weave.works/template-name: aks-template
    templates.weave.works/template-namespace: default
  name: pesto-conformance2023
  namespace: default
spec:
  clusterNetwork:
    services:
      cidrBlocks:
        - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureManagedControlPlane
    name: pesto-conformance2023
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureManagedCluster
    name: pesto-conformance2023

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedControlPlane
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: aks-template
    templates.weave.works/template-namespace: default
  name: pesto-conformance2023
  namespace: default
spec:
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureClusterIdentity
    name: cluster-identity
  location: eastus
  resourceGroupName: team-pesto-use1
  subscriptionID: ace37984-3d07-4051-9002-d5a52c0ae14b
  version: 1.25.5

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedCluster
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: aks-template
    templates.weave.works/template-namespace: default
  name: pesto-conformance2023
  namespace: default

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: aks-template
    templates.weave.works/template-namespace: default
  name: pesto-conformance2023-pool0
  namespace: default
spec:
  clusterName: pesto-conformance2023
  replicas: 2
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: pesto-conformance2023
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: pesto-conformance2023-pool0
      version: 1.25.5

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: aks-template
    templates.weave.works/template-namespace: default
  name: pesto-conformance2023-pool0
  namespace: default
spec:
  mode: System
  name: pool0
  sku: Standard_D2s_v3

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: aks-template
    templates.weave.works/template-namespace: default
  name: pesto-conformance2023-pool1
  namespace: default
spec:
  clusterName: pesto-conformance2023
  replicas: 3
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: pesto-conformance2023
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: pesto-conformance2023-pool1
      version: 1.25.5

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    templates.weave.works/template-name: aks-template
    templates.weave.works/template-namespace: default
  name: pesto-conformance2023-pool1
  namespace: default
spec:
  mode: User
  name: pool1
  sku: Standard_D2s_v3

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
    templates.weave.works/template-name: aks-template
    templates.weave.works/template-namespace: default
  name: cluster-identity
  namespace: default
spec:
  allowedNamespaces: {}
  clientID: 626d016a-9788-442c-b062-3ed7e64340db
  clientSecret:
    name: cluster-identity-secret
    namespace: default
  tenantID: 3747a928-2079-440f-8f0f-ab1be2a7c058
  type: ServicePrincipal
