apiVersion: v1
data:
  abcABC123!@#><: ENC[AES256_GCM,data:UJj3Y1Jr7YMYWekzqgl9J/EEbRo=,iv:kMBX8u3S0JQY1eRzagmonrUzYPwfFpdEoZs+lG5mZv8=,tag:hXsgz34GALc2RAxaikFG2w==,type:str]
kind: Secret
metadata:
  name: newSecretTest
  namespace: test-secret-ns
sops:
  age: null
  azure_kv: null
  encrypted_regex: ^(data|stringData)$
  gcp_kms: null
  hc_vault: null
  kms: null
  lastmodified: "2023-05-16T18:38:40Z"
  mac: ENC[AES256_GCM,data:CrOxHPZFNLnCtOD2WlE6XTh5DemgiLwt/A9UMQTKv4/ZNSCM2DF1ip4xSX6QFVjomeMaYexZC8cnj30GomAXpgKYGUgeymVsyt58bbC3YeU295WWLNb6e95Nx/kr/W3/AwEVxyqxvKH8PXeausMFyDca/lsv2wGiYYfX7DKvkvc=,iv:lprIqtEFNbdn4XOM+LL7zACf0o+p+AKyfmj4+MGW4+8=,tag:q9duP2sjAufxB6rRAqmNLA==,type:str]
  pgp:
  - created_at: "2023-05-16T18:38:40Z"
    enc: |
      -----BEGIN PGP MESSAGE-----

      hQIMA2XEMZaCVgElAQ/+Ksd6gZIKeZ2oc1FIt5F7OjDy/m+OcwL6KcpGQLTybBPs
      3JWHzewqxT6e89q37AP9GIG411i1dgYQZKc4DnnOOzLrgPb+eXZYvfTgpHXIGh0D
      BAk4xS1/tY16rxQQtL0/E2XvfW+FMk2BM7QJAtOyBvkX6SRp0xiMgUsnGHjzLG0Y
      mKo9L6T6SSvbGZJGRU8jKAanR85RuW8UIPMooN/HHA1wrMqKxwVNhOaWVny680AZ
      GrG2qSKCv8ZXZ4rKxUw8ytKeUe2SoPVlq0QGBO1IhxDZFRUfS/F5JOs4+pYSHTAC
      OTNfBpVmCHkzpIgzLJZ41iZr/PANXmMxFRPpOfGBXRqpF3J32rOJ0IZQGjQ9T4Ex
      B6oM59uxMMLR14nyONVe0sIKWL7gS9jkeeucZGk96FhuZ+gWJkoHWZ/IDI09W25l
      9x3m/s3PY8vrqmH9ZvQqP3S9w1alaXGxrJIiJUewV9txw053bscjPOb9wiMlivGS
      SU6yoJGaHJqYHaCk0sDJBUlV6chMUXezvrYhcAHL8mcxbcJj1GSaAzcBxh4ZZ0hP
      jSeh+HT8bw0QUUDodoQ+boVPrMs45evK1DkWW3a6YH7w7Lmfc4CCi+paU1EbNrPw
      dp6ijKpYVRhn7U7dhw53IR1jZOYfStwHgH0VO5/cUbJRc0/A3gvPjS7Rh1vWKavS
      XgGw6mOvWXpZyGBVM2A+tAbQGpF+xLd8UyMI1OHVC9V+RRA2/k3yx1BsvEGa1I7P
      vtFNJB5Mb9q+Fjbgc1zM+OuVJA9Nbr2BwDhru9YpxcL6Ol5IFuTtS7w+nzlxRS0=
      =9Cl2
      -----END PGP MESSAGE-----
    fp: 0c64d144879439d38364647e9a2fcf408f708b63
  version: ""
