apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: sync-secrets-remote
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 20s
  path: ./eksctl-clusters/terraform/sync-secrets-remote
  approvePlan: auto
  destroyResourcesOnDeletion: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

