apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: null
  name: weave-policy-agent
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-policy-agent
      sourceRef:
        apiVersion: source.toolkit.fluxcd.io/v1beta2
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
      version: 2.0.0
  interval: 10m0s
  targetNamespace: default
  values: null
status: {}
