apiVersion: pipelines.weave.works/v1alpha1
kind: Pipeline
metadata:
  name: dex
  namespace: dex
spec:
  appRef:
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: dex
  environments:
    - name: dev
      targets:
        - clusterRef:
            kind: GitopsCluster
            name: pentest-leaf
            namespace: flux-system