apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: shared-secrets
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./eksctl-clusters/shared-secrets
  prune: true
  validation: client
  decryption:
    provider: sops
  postBuild:
    substitute:
      ISSUER_URL: aHR0cHM6Ly9hdXRvbWF0aW9uLXRlc3RzLWRleC5lbmctc2FuZGJveC53ZWF2ZS53b3Jrcw==
      REDIRECT_URL: aHR0cHM6Ly9hdXRvbWF0aW9uLXRlc3RzLmVuZy1zYW5kYm94LndlYXZlLndvcmtzL29hdXRoMi9jYWxsYmFjaw==
