apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: null
  name: external-secrets
  namespace: flux-system
spec:
  chart:
    spec:
      chart: external-secrets
      sourceRef:
        apiVersion: source.toolkit.fluxcd.io/v1beta2
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
      version: 0.6.1
  interval: 10m0s
  targetNamespace: external-secrets
  values:
    external-secrets:
      installCRDs: true
    secretsSource:
      branch: main
      enabled: true
      path: ./clusters/secrets/management/
      secretRef: ssh-creds
      url: ssh://git@github.com/waleedhammam/wge-dev
status: {}
