apiVersion: v1
data:
  password: ENC[AES256_GCM,data:agdyoSO+BGejPuQ9,iv:6KA2joNEMqbjISCo2JptEJXQkNsSXDQIyAxnuBTm6wM=,tag:3NoV4mzS7yle21PtGHnQ3w==,type:str]
kind: Secret
metadata:
  name: test-secret-sops
  namespace: flux-system
sops:
  age: null
  azure_kv: null
  encrypted_regex: ^(data|stringData)$
  gcp_kms: null
  hc_vault: null
  kms: null
  lastmodified: "2023-05-10T08:37:51Z"
  mac: ENC[AES256_GCM,data:KIyYxY5Iwikj6wk9f5QuPS2IrRpAWEoSBiGK8jwBkb22AplLILd7GqXwqPQcmlskpXSqIGAQMUPNnOQVxF2NMyltG+oiZdXH0ZZ2/HN/U9TRrVKktbOcsoJ28XOsIYPz4ly4k9JPD7yTvymywbz9FrlD6tbgRIW8zl8LnDSUPiY=,iv:/iqF27yXKvuFtHT/SLP3AJLjEvWXHWe+7VCb/4fkpIM=,tag:is93JVe8ydHw5BENdx5jGA==,type:str]
  pgp:
  - created_at: "2023-05-10T08:37:51Z"
    enc: |
      -----BEGIN PGP MESSAGE-----

      hQIMA130jN3G1p6cARAArmwo1FCUHHSlhu9I9x6Iohrou+/buL2/eAOLItNOTR34
      xVOMmj5cL2mJ+NSquZ5buLY+SJpV0zvEo1EeQ8xLJnrDpFqOtREQegYe3vVkKXGo
      5gclCu72WyD/ECZYWFvAFWl01JfPBgQV7t7e/ty4N0c4w7WAXHrPDzCJ99Wc/vAd
      o6CRAybVYAhS+Mn7BTrtmqCAK/nd2AJodIN8W0WJBptG3NteGfs95ORzxZRI64KZ
      lFzNKJ1ZevT8nI3rOP9J+3SRL7oWxJa5dCAaK09K3Tn3RdHBsFm8byUWTQ0cjY4l
      IVs/QeWN1EZNtPDve/PK36cDAy+XxNq3b1Pj4ucxl7ytLrDzXLv4q+5QE6t7TZ9c
      FjiYcpIfzvqncBh7Z6eYyACQm0A23vNXoK4A1GL0+XiPIFXukgpfKYXJ9xbZlmsG
      LtO9uOCH6BB9LHNQwXYzAWFf6L/6S6gPDBzbBU0U3orYyD4ZKSV3tGZKk48cS2dN
      7r8/xFq7545L/UNCqoYDCIhQveFS41rNL8NNkN8fbGHcbE68audc5oCYJtM+XjD8
      7o8Rs+MOLix/+wbg1MmtoYdxVcgnN0wUUYYU3YLovk2htGunCS5/NJieN54o5NkQ
      cWlyj+ecKGJLAalEG0bHN66W0uJ7Ohkzt38CIscBksLGxarOGUYKCoBP6eDVWgDS
      XgHhzZFaVdXXLnXinlnC1IyzsnNurT4rd13iYHo7zPZGbOIeX/uSDHk0ArrSUeJJ
      KlwntZQ7ec/NcXsLrF3THY0ufqtD2A3Gn52eZHe/JaVm/RJPocAk1wZgJrLaz8E=
      =Mwhu
      -----END PGP MESSAGE-----
    fp: ab77563812c53aa1f74d87a9e8412f6663a1470e
  version: ""
