{{- $labels := (include "external-secrets-config.labels" .) -}}
{{- range $key, $store := .Values.secretStores }}
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: {{ $key }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  {{- toYaml $store | nindent 2 }}
---
{{- end -}}
