name: create-cluster

on:
  create:
    branches: "*"

jobs:
  provision-cluster:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Get branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: get_branch
      - name: Echo script
        run: echo "Provisioning cluster ${{ steps.get_branch.outputs.branch }}..."

      - name: Install aws-cli
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version

      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin
          eksctl version

      - name: Install flux
        run: |
          curl --silent --location https://github.com/fluxcd/flux2/releases/download/v0.32.0/flux_0.32.0_$(uname -s)_amd64.tar.gz | tar xz -C /tmp
          sudo mv /tmp/flux /usr/local/bin
          flux version --client

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::894516026745:role/WeaveEksGithubActions
          aws-region: eu-north-1

      - name: Create cluster
        run: |
          $GITHUB_WORKSPACE/eksctl-clusters/scripts/request-cluster.sh --cluster-name testme
          $GITHUB_WORKSPACE/eksctl-clusters/scripts/provision-cluster.sh --cluster-name testme

      - name: Test eksctl
        run: |
          eksctl get clusters --region eu-north-1
