name: delete-cluster

on:
  delete:
    branches: "*"

jobs:
  delete-cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: get_branch
      - name: Echo script
        run: echo "Deleting cluster ${{ steps.get_branch.outputs.branch }}..."
