name: Delete EKS Cluster

on:
  delete:
    branches: '**'
  workflow_dispatch:
    inputs:
      cluster-name:
        description: "Cluster Name"
        required: true
        type: string

env:
  AWS_REGION: "eu-north-1"

jobs:
  delete-cluster:
    if: ${{ startsWith(github.event.ref, 'cluster-') || (github.event_name == 'workflow_dispatch')}}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Install aws-cli
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version

      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/v0.109.0//eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin
          eksctl version

      - name: Install helm
        uses: azure/setup-helm@v2.0
        with:
          version: v3.8.2

      - name: Install kubectl
        uses: Azure/setup-kubectl@v2.0
        with:
          version: v1.23.7

      - name: Install flux
        run: |
          curl --silent --location https://github.com/fluxcd/flux2/releases/download/v0.33.0/flux_0.33.0_$(uname -s)_amd64.tar.gz | tar xz -C /tmp
          sudo mv /tmp/flux /usr/local/bin
          flux version --client

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::894516026745:role/WeaveEksGithubActions
          aws-region: ${{ env.AWS_REGION }}

      - name: Export Cluster Name if Branch Deleted
        if: ${{ startsWith(github.event.ref, 'cluster-') }}
        run: |
          export BRANCH_NAME=${{ github.event.ref }}
          export CLUSTER_NAME=${BRANCH_NAME#cluster-}
          echo "CLUSTER_NAME=${CLUSTER_NAME}" >> $GITHUB_ENV

      - name: Export Cluster Name if Triggered Manually
        if: ${{ (github.event_name == 'workflow_dispatch') }}
        run: |
          echo "CLUSTER_NAME=${{ inputs.cluster-name }}" >> $GITHUB_ENV

      - name: kubeconfig
        run: |
          echo "Cluster: ${{ env.CLUSTER_NAME }}"
          eksctl utils write-kubeconfig --region ${{ env.AWS_REGION }} --cluster ${{ env.CLUSTER_NAME }} --kubeconfig=$HOME/.kube/config
          kubectl get nodes

      - name: Delete Cluster
        run: |
          export GITHUB_TOKEN=${{ secrets.WEAVE_GITOPS_BOT_TOKEN_CLUSTERS_CONFIG }}
          echo "Deleting ${{ env.CLUSTER_NAME }} cluster ..."
          $GITHUB_WORKSPACE/eksctl-clusters/scripts/destroy-cluster.sh --cluster-name ${{ env.CLUSTER_NAME }}

      - name: Check running clusters
        run: |
          eksctl get clusters --region ${{ env.AWS_REGION }}
