name: Provision EKS Cluster

on:
  create:
    branches: '**'

env:
  AWS_REGION: "eu-north-1"
  CLUSTERCTL_VERSION: "v1.2.0"
  CLUSTER_AWS_ADM_VERSION: "v1.5.0"
  EKSCTL_VERSION: "v0.109.0"

jobs:
  provision-cluster:
    if: startsWith(github.event.ref, 'cluster-')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Install aws-cli
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::894516026745:role/WeaveEksGithubActions
          aws-region: ${{ env.AWS_REGION }}

      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/${{ env.EKSCTL_VERSION }}/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin
          eksctl version

      - name: Install helm
        uses: azure/setup-helm@v2.0
        with:
          version: v3.8.2

      - name: Install kubectl
        uses: Azure/setup-kubectl@v2.0
        with:
          version: v1.23.7

      - name: Install flux
        run: |
          curl --silent --location https://github.com/fluxcd/flux2/releases/download/v0.33.0/flux_0.33.0_$(uname -s)_amd64.tar.gz | tar xz -C /tmp
          sudo mv /tmp/flux /usr/local/bin
          flux version --client

      - name: Install clusterctl
        run: |
          curl -L https://github.com/kubernetes-sigs/cluster-api/releases/download/${{ env.CLUSTERCTL_VERSION }}/clusterctl-linux-amd64 -o clusterctl
          chmod +x ./clusterctl
          sudo mv ./clusterctl /usr/local/bin/clusterctl
          clusterctl version

      - name: install clusterawsadm
        run: |
          curl -L https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/download/${{ env.CLUSTER_AWS_ADM_VERSION }}/clusterawsadm-linux-amd64 -o clusterawsadm
          chmod +x clusterawsadm
          sudo mv clusterawsadm /usr/local/bin
          clusterawsadm version

      - name: install clusterawsadm stack
        run: |
          STACK=$(aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE --region ${{ env.AWS_REGION }} | grep wge-capi-cluster-api-provider-aws-sigs-k8s-io || true)
          echo "Stack: $STACK"
          if [ -z "$STACK" ]; then
            echo "Create clusterawsadm stack"
            clusterawsadm bootstrap iam create-cloudformation-stack --config ./eksctl-clusters/aws_bootstrap_config.yaml --region=${{ env.AWS_REGION }}
          fi

      - name: Provision Cluster
        run: |
          export GITHUB_TOKEN=${{ secrets.WEAVE_GITOPS_BOT_TOKEN_CLUSTERS_CONFIG }}
          export BRANCH_NAME=${{ github.event.ref }}
          export CLUSTER_NAME=${BRANCH_NAME#*cluster-}
          echo "Provisioning $CLUSTER_NAME cluster ..."
          $GITHUB_WORKSPACE/eksctl-clusters/scripts/provision-cluster.sh --cluster-name $CLUSTER_NAME

      - name: Check running clusters
        run: |
          eksctl get clusters --region ${{ env.AWS_REGION }}

      - name: kubeconfig
        run: |
          export BRANCH_NAME=${{ github.event.ref }}
          export CLUSTER_NAME=${BRANCH_NAME#*cluster-}
          echo $CLUSTER_NAME
          eksctl utils write-kubeconfig --region ${{ env.AWS_REGION }} --cluster ${CLUSTER_NAME} --kubeconfig=$HOME/.kube/config
          kubectl get nodes

      - name: clusterctl init --infrastructure aws => connect using the cluster user.
        run: |
          export AWS_B64ENCODED_CREDENTIALS=$(clusterawsadm bootstrap credentials encode-as-profile --region ${{ env.AWS_REGION }})
          export EXP_EKS=true
          export EXP_MACHINE_POOL=true
          export CAPA_EKS_IAM=true
          export EXP_CLUSTER_RESOURCE_SET=true

          clusterctl init --infrastructure aws
          kubectl get deploy -A
