name: Mark stale PRs
on:
  workflow_dispatch: {}
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    env:
      days-before-pr-stale: 7
      days-before-pr-close: 3
    steps:
    - uses: actions/stale@v6
      with:
        repo-token: ${{ secrets.WEAVE_GITOPS_BOT_TOKEN_CLUSTERS_CONFIG }}
        days-before-pr-stale: ${{ env.days-before-pr-stale }}
        days-before-pr-close: ${{ env.days-before-pr-close }}
        stale-pr-message: 'This PR is stale because it has been open for ${{ env.days-before-pr-stale }} days with no activity. Remove stale label or comment, otherwise this PR will be closed in ${{ env.days-before-pr-close }} days.'
        close-pr-message: 'This PR was closed because it has been stalled for ${{ env.days-before-pr-close }} days with no activity.'
        stale-pr-label: 'stale'
        exempt-pr-labels: 'keep'
        delete-branch: true

        days-before-issue-stale: -1
        days-before-issue-close: -1
