apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  creationTimestamp: null
  name: all-prop
  namespace: flux-system
spec:
  dataFrom:
  - extract:
      key: /dev/waleed
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    creationPolicy: Owner
    name: all-prop
status:
  refreshTime: null
