apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  creationTimestamp: null
  name: multiple-prop
  namespace: flux-system
spec:
  data:
  - remoteRef:
      key: /dev/waleed
      property: dev
    secretKey: dev
  - remoteRef:
      key: /dev/waleed
      property: another
    secretKey: test
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: SecretStore
    name: aws-secret-store
  target:
    creationPolicy: Owner
    name: multiple-prop
status:
  refreshTime: null
