apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  creationTimestamp: null
  name: elnew-secret
  namespace: flux-system
spec:
  data:
  - remoteRef:
      key: test_external_secrets
      property: testwaleed_secretmanagment
    secretKey: elnew-secret
  refreshInterval: 10s
  secretStoreRef:
    kind: SecretStore
    name: aws-secret-store
  target:
    creationPolicy: Owner
    name: brand-new-secret
status:
  refreshTime: null
